### ISSUE TITLE
MS Reading View Collation Bugs

### ISSUE THREAD

**Issue by ebeshero** [FrankensteinVariorum/fv-postCollation#48]
Running list of bad MS reading view passages with bugs: 

This set of bugs: can't click on passage--no sidepanel display in any of the witnesses:
- [x] https://frankensteinvariorum.org/viewer/MS/box_c56_from_chapter_1/#C08_app50 , https://frankensteinvariorum.org/viewer/1818/vol_1_chapter_i/#C08_app50  (etc)

In the next set of bugs, the reading view drops text that you can see in the side panel. Help keep a running list of these to fix! 

- [x]  https://frankensteinvariorum.org/viewer/MS/box_c56_from_chapter_1/#C08_app57 
- [x] https://frankensteinvariorum.org/viewer/MS/box_c56_chap_11/#C14_app215 "Mad e Lavenz" passage is not showing as deleted."

**Comment by nhammer514** [comment]
- [x] BOX56 CHAP 2
 - Cannot click on first chunk of text

- [x] BOX56 CHAP 4
 - "all changed. t and the expulsion of chimera overthrew at"

- [x] BOX56 CHAP 5
 - "on e ^c e ^. on" [XML parsing error] https://frankensteinvariorum.org/viewer/MS/box_c56_chap_5/#C09_app322
 - "contrary t ^T he big information I had obtained was "
 - [x] BOX56 CHAP 6**** 
 - cannot click on "but ^Yet ^But when I when I looked around for ^considered my materials they The materials at present within ^ my command "
 - "hope and And altho although I could not hope"
 - "way perfect ' yet ' ^but Nor, "
 - "I had ^had t"

- [x] C09
 - Fix ending with longToken, otherwise postProcessing will drop text. 

- [x] BOX56 CHAP 8
 - docile yet ^& weak as
 -  illness had made me in my then condition
 - waldman —%q%dam m n %q%the fellow,%q%
 - %q%of countenance.—Aye, Aye,

**Comment by Yuying-Jin** [comment]
> * [x]   https://frankensteinvariorum.org/viewer/MS/box_c56_from_chapter_1/#C08_app57


broken at P5-Pt5

**Comment by ebeshero** [comment]
All bugs reported here are repaired!
